// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7du2dbI7yGo5Akmy5ejovBTozQvd4Vqo',
    appId: '1:253030228111:web:d5ac18a3dd52d7e3fe50fa',
    messagingSenderId: '253030228111',
    projectId: 'distance-check-app-tst',
    authDomain: 'distance-check-app-tst.firebaseapp.com',
    storageBucket: 'distance-check-app-tst.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA66igHQZodk1B-qg2-5bgPSkVKUILqEfw',
    appId: '1:253030228111:android:39cd275f72ede10afe50fa',
    messagingSenderId: '253030228111',
    projectId: 'distance-check-app-tst',
    storageBucket: 'distance-check-app-tst.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGI4PmU_ZSifJ_z9GcfzEEvIbod4GQ-z0',
    appId: '1:253030228111:ios:c728ba8d66082b64fe50fa',
    messagingSenderId: '253030228111',
    projectId: 'distance-check-app-tst',
    storageBucket: 'distance-check-app-tst.appspot.com',
    iosBundleId: 'com.example.distanceCheckApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7du2dbI7yGo5Akmy5ejovBTozQvd4Vqo',
    appId: '1:253030228111:web:296be257ba039982fe50fa',
    messagingSenderId: '253030228111',
    projectId: 'distance-check-app-tst',
    authDomain: 'distance-check-app-tst.firebaseapp.com',
    storageBucket: 'distance-check-app-tst.appspot.com',
  );
}
